# Generated by Django 2.2.4 on 2019-09-11 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('author_first_name', models.CharField(default='', max_length=100)),
                ('author_second_name', models.CharField(default='', max_length=100)),
                ('article_cover', models.ImageField(default='', upload_to='images/')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('article_summary', models.CharField(max_length=2000)),
                ('article_paragraph1', models.TextField(blank=True, default='')),
                ('article_paragraph2', models.TextField(blank=True, default='')),
                ('article_paragraph3', models.TextField(blank=True, default='')),
                ('article_paragraph4', models.TextField(blank=True, default='')),
                ('article_paragraph5', models.TextField(blank=True, default='')),
                ('article_paragraph6', models.TextField(blank=True, default='')),
                ('article_paragraph7', models.TextField(blank=True, default='')),
                ('article_category', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Category')),
            ],
        ),
    ]
