# Generated by Django 2.2.4 on 2019-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_video_link',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
