# Generated by Django 2.2.3 on 2019-07-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20190726_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_cover',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
