# Generated by Django 2.2.4 on 2019-09-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_article_article_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
