# Generated by Django 2.2.3 on 2019-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_article_article_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
