# Generated by Django 2.2.3 on 2019-07-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_number',
            field=models.IntegerField(default=0),
        ),
    ]
