# Generated by Django 2.2.3 on 2019-07-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_article_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
