# Generated by Django 2.2.3 on 2019-08-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20190731_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_summary',
        ),
    ]
